### ISSUE TITLE
GitHub Issue Manager: NoSuchPageException

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#7]
I've encountered an exception thrown by the GitHubManager when iterating issues. The project in question doesn't use the Issue tracker on GitHub, so I'm not sure if this is an issue with the GitHub importer, or with the GitHub manager (or both). It looks like the project _used_ to use the issue tracker, but have since removed it, which may be the root of the cause. I guess that, at the least, the GitHubManager needs to catch the exception and continue gracefully. But perhaps the importer shouldn't importer the issue tracker as well.

Steps to reproduce:
- Import project

``` java
GitHubRepository librePlan = ghImporter.importRepository("Igalia/libreplan", platform); 
librePlan.getBugTrackingSystems().add(createBugzilla("http://bugs.libreplan.org/xmlrpc.cgi", "LibrePlan", null));       
```
- Try to calculate first date of the BTS

``` java
PlatformBugTrackingSystemManager manager = new ExtensionPointBugTrackingSystemManager(platform);
for (BugTrackingSystem bts : p.getBugTrackingSystems()) {
    manager.getFirstDate(null, bts)
}
```
- The following exception was thrown

```
org.eclipse.egit.github.core.client.NoSuchPageException: Not Found (404)
    at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:175)
    at org.ossmeter.platform.bugtrackingsystem.github.GitHubManager.getEarliestIssueDate(GitHubManager.java:135)
    at org.ossmeter.platform.bugtrackingsystem.github.GitHubManager.getFirstDate(GitHubManager.java:72)
    at org.ossmeter.platform.bugtrackingsystem.github.GitHubManager.getFirstDate(GitHubManager.java:1)
    at org.ossmeter.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getFirstDate(PlatformBugTrackingSystemManager.java:72)
    at org.ossmeter.playpen.ProjectCreatorApplication.start(ProjectCreatorApplication.java:136)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
    at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
    at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:740)
    at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
    ... 18 more
```

**Comment by yannisKork** [comment]
Hi jrwilliams,

is this a GitHub Issue Manager problem, or a Bugzilla manager problem? It looks like its the latter, because the url is pointing to Bugzilla. I am just asking to make sure that I understood correctly. 

Cheers,
yannisKork

**Comment by jrwilliams** [comment]
Ah yes, sorry. I didn't make my code very clear. The first line:

``` java
GitHubRepository librePlan = ghImporter.importRepository("Igalia/libreplan", platform); 
```

imports the project from GitHub. The import process adds a BTS to the project that is of type GitHubBugTracker. This tracker isn't actually used by the project, and can't be seen on the project's web page (https://github.com/Igalia/libreplan). 

The next line adds the issue tracker that the project actually uses:

``` java
librePlan.getBugTrackingSystems().add(createBugzilla("http://bugs.libreplan.org/xmlrpc.cgi", "LibrePlan", null)); 
```

I included that line for completeness, but really it can be ignored. The issue is that the GitHubManager is trying to get the first date of the GitHubBugTracker but is throwing an exception (the stack trace shows the GitHubManager working). So perhaps the importer shouldn't have imported the GitHubBugTracker (but I don't know whether the GitHub API shows that the issue tracker isn't used), but the GitHubManager needs to be able to gracefully handle the exception.

Looking at the JSON in Mongo, the issue might actually arise from a bug in the importer. The JSON for the GitHubBugTracker is below:

``` json
{
    "_id" : "ab9965a8-6bd2-42c4-a922-1eef265e6542",
    "_type" : "org.ossmeter.repository.model.github.GitHubBugTracker",
    "persons" : [],
    "issues" : [ ... ],
    "_superTypes" : [ 
        "org.ossmeter.repository.model.github.BugTrackingSystem"
    ],
    "_ossmeterId" : "null/null:github"
}
```

I'm not familiar with how the GitHubManager works, but I don't see any valid details for how it can connect to the issue tracker? The "_ossmeterId" doesn't look correct. @md2manoppello @davidediruscio  any thoughts?

Cheers,
Jim

**Comment by jdirocco** [comment]
Ok I have fixed this bug. The GitHubBugTracker's url field was null. Now, I set to default https://api.github.com/repos/_projectId_/issues.
@jrwilliams, can you test again?

**Comment by jrwilliams** [comment]
Hi Juri,

The URL is now not null, but the GitHubManager is still throwing the same exception. I've encountered this on the assimp project as well (https://github.com/assimp/assimp) now.

**Comment by jdirocco** [comment]
Hi @jrwilliams,
In order to fix this issue, Could I have an example url for GitHubManager?In json resource there are few informations about bug tracking system. For instance, the _assimp_ project json resource has only the following informations about issues.

```
{
    ...
    "has_issues": true,
    ...
    "issue_comment_url": "https://api.github.com/repos/assimp/assimp/issues/comments/{number}",
    "issue_events_url": "https://api.github.com/repos/assimp/assimp/issues/events{/number}",
    "issues_url": "https://api.github.com/repos/assimp/assimp/issues{/number}",
    ...
    "open_issues": 117,
    "open_issues_count": 117,
}
```

Maybe, @yannisKork could give more requirements about the typical url patter.

**Comment by jrwilliams** [comment]
If you look at `GitHubManager.java`, there's a main method that I believe Jacob was using for testing. It appears that the important fields are "user" and "repository":

``` java
GitHubBugTracker bugTracker = new GitHubBugTracker();
bugTracker.setUser("sampsyo");
bugTracker.setRepository("beets");

Date date = new Date(new DateTime(2014, 7, 14, 0, 0).toDate());

GitHubManager github = new GitHubManager();
GitHubBugTrackingSystemDelta delta = (GitHubBugTrackingSystemDelta) github
                .getDelta(null, bugTracker, date);
```

My guess is that the manager doesn't use the "url" field at all?

**Comment by jrwilliams** [comment]
We're getting this exception again for the Jahia Newsletter project (https://github.com/Jahia/JahiApp-Newsletter). Has there been any progress on this?

(Edited because I put the wrong project in!)

**Comment by yannisKork** [comment]
We have sorted the issue. The problem was that the github manager does not use the url field, but instead builds the url from the fields user and repository. So, the manager needs a gitHubBugTracker with user and repository fields set, as follows:

githubBugTracker.setUser("Igalia");
githubBugTracker.setRepository("libreplan");

Could you please update the importer to set these fields when creating the issue tracker?
